### ISSUE TITLE
Failed to compile addItem

### ISSUE THREAD

**Issue by Jvalal-zz** [jameshamann/serverless-graphql-react-webapp#1]
Hello - Getting a failed to compile error

![image](https://user-images.githubusercontent.com/3803053/49529494-fb3b7600-f86a-11e8-8941-fead7b9bcdd3.png)

![image](https://user-images.githubusercontent.com/3803053/49529502-01315700-f86b-11e8-8519-db568ab15559.png)

**Comment by jameshamann** [comment]
Hey @Jvalal, apologies, I forgot to mention to install Material UIs icon library in the blog post, I've updated the post on medium now. 

To overcome the error run:

`yarn add @material-ui/icons`

Thanks!
